### ISSUE TITLE
Cannot update Jason to 1.3.0

### ISSUE THREAD

**Issue by omar8792** [primait/auth0_ex#53]
https://github.com/primait/auth0_ex/blob/97c3daa9fdd5fd19ec08227fac5bba6ed731fbba/mix.exs#L38

I sugget to relax Jason version to 1.2 or update to 1.3

**Comment by dallagi** [comment]
Thanks for the issue! 
This is addressed by https://github.com/primait/auth0_ex/pull/52 , which should get merged soon :slightly_smiling_face:

**Comment by dallagi** [comment]
Released with version `0.3.0-rc.1.3`
